<?php

/**
 * Copyright (C) 2016-2020 Benjamin Heisig
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 * @author Benjamin Heisig <https://benjamin.heisig.name/>
 * @copyright Copyright (C) 2016-2020 Benjamin Heisig
 * @license http://www.gnu.org/licenses/agpl-3.0 GNU Affero General Public License (AGPL)
 * @link https://github.com/bheisig/i-doit-api-client-php
 */

declare(strict_types=1);

namespace bheisig\idoitapi\Constants;

interface Category {

    const CATG__GLOBAL = 'C__CATG__GLOBAL';
    const CATG__MODEL = 'C__CATG__MODEL';
    const CATG__FORMFACTOR = 'C__CATG__FORMFACTOR';
    const CATG__CPU = 'C__CATG__CPU';
    const CATG__MEMORY = 'C__CATG__MEMORY';
    const CATG__NETWORK = 'C__CATG__NETWORK';
    const CATG__STORAGE = 'C__CATG__STORAGE';
    const CATG__POWER_CONSUMER = 'C__CATG__POWER_CONSUMER';
    const CATG__UNIVERSAL_INTERFACE = 'C__CATG__UNIVERSAL_INTERFACE';
    const CATG__APPLICATION = 'C__CATG__APPLICATION';
    const CATG__ACCESS = 'C__CATG__ACCESS';
    const CATG__BACKUP = 'C__CATG__BACKUP';
    const CATG__EMERGENCY_PLAN = 'C__CATG__EMERGENCY_PLAN';
    const CATG__FILE = 'C__CATG__FILE';
    const CATG__CONTACT = 'C__CATG__CONTACT';
    const CATG__LOGBOOK = 'C__CATG__LOGBOOK';
    const CATG__CONTROLLER = 'C__CATG__CONTROLLER';
    const CATG__LOCATION = 'C__CATG__LOCATION';
    const CATG__IMAGE = 'C__CATG__IMAGE';
    const CATG__MANUAL = 'C__CATG__MANUAL';
    const CATG__OVERVIEW = 'C__CATG__OVERVIEW';
    const CATG__SOUND = 'C__CATG__SOUND';
    const CATG__OBJECT = 'C__CATG__OBJECT';
    const CATG__GRAPHIC = 'C__CATG__GRAPHIC';
    const CATG__VIRTUAL_MACHINE = 'C__CATG__VIRTUAL_MACHINE';
    const CATG__ACCOUNTING = 'C__CATG__ACCOUNTING';
    const CATG__NETWORK_PORT = 'C__CATG__NETWORK_PORT';
    const CATG__NETWORK_INTERFACE = 'C__CATG__NETWORK_INTERFACE';
    const CATG__NETWORK_LOG_PORT = 'C__CATG__NETWORK_LOG_PORT';
    const CATG__DRIVE = 'C__CATG__DRIVE';
    const CATG__STORAGE_DEVICE = 'C__CATG__STORAGE_DEVICE';
    const CATG__CONTROLLER_FC_PORT = 'C__CATG__CONTROLLER_FC_PORT';
    const CATG__SANPOOL = 'C__CATG__SANPOOL';
    const CATG__IP = 'C__CATG__IP';
    const CATG__VERSION = 'C__CATG__VERSION';
    const CATG__CABLING = 'C__CATG__CABLING';
    const CATG__CONNECTOR = 'C__CATG__CONNECTOR';
    const CATG__INVOICE = 'C__CATG__INVOICE';
    const CATG__CUSTOM_FIELDS = 'C__CATG__CUSTOM_FIELDS';
    const CATG__POWER_SUPPLIER = 'C__CATG__POWER_SUPPLIER';
    const CATG__RAID = 'C__CATG__RAID';
    const CATG__LDEV_SERVER = 'C__CATG__LDEV_SERVER';
    const CATG__LDEV_CLIENT = 'C__CATG__LDEV_CLIENT';
    const CATG__HBA = 'C__CATG__HBA';
    const CATG__CLUSTER_ROOT = 'C__CATG__CLUSTER_ROOT';
    const CATG__CLUSTER = 'C__CATG__CLUSTER';
    const CATG__SHARES = 'C__CATG__SHARES';
    const CATG__CLUSTER_SERVICE = 'C__CATG__CLUSTER_SERVICE';
    const CATG__CLUSTER_MEMBERS = 'C__CATG__CLUSTER_MEMBERS';
    const CATG__CLUSTER_SHARED_STORAGE = 'C__CATG__CLUSTER_SHARED_STORAGE';
    const CATG__CLUSTER_MEMBERSHIPS = 'C__CATG__CLUSTER_MEMBERSHIPS';
    const CATG__COMPUTING_RESOURCES = 'C__CATG__COMPUTING_RESOURCES';
    const CATG__CLUSTER_VITALITY = 'C__CATG__CLUSTER_VITALITY';
    const CATG__SNMP = 'C__CATG__SNMP';
    const CATG__VIRTUAL_HOST_ROOT = 'C__CATG__VIRTUAL_HOST_ROOT';
    const CATG__VIRTUAL_HOST = 'C__CATG__VIRTUAL_HOST';
    const CATG__GUEST_SYSTEMS = 'C__CATG__GUEST_SYSTEMS';
    const CATG__VIRTUAL_MACHINE__ROOT = 'C__CATG__VIRTUAL_MACHINE__ROOT';
    const CATG__VIRTUAL_SWITCH = 'C__CATG__VIRTUAL_SWITCH';
    const CATG__VIRTUAL_DEVICE = 'C__CATG__VIRTUAL_DEVICE';
    const CATG__CLUSTER_SHARED_VIRTUAL_SWITCH = 'C__CATG__CLUSTER_SHARED_VIRTUAL_SWITCH';
    const CATG__BACKUP__ASSIGNED_OBJECTS = 'C__CATG__BACKUP__ASSIGNED_OBJECTS';
    const CATG__GROUP_MEMBERSHIPS = 'C__CATG__GROUP_MEMBERSHIPS';
    const CATG__IT_SERVICE_COMPONENTS = 'C__CATG__IT_SERVICE_COMPONENTS';
    const CATG__ITS_LOGBOOK = 'C__CATG__ITS_LOGBOOK';
    const CATG__IT_SERVICE = 'C__CATG__IT_SERVICE';
    const CATG__OBJECT_VITALITY = 'C__CATG__OBJECT_VITALITY';
    const CATG__RELATION = 'C__CATG__RELATION';
    const CATG__IT_SERVICE_RELATIONS = 'C__CATG__IT_SERVICE_RELATIONS';
    const CATG__DATABASE_ASSIGNMENT = 'C__CATG__DATABASE_ASSIGNMENT';
    const CATG__ITS_TYPE = 'C__CATG__ITS_TYPE';
    const CATG__PASSWD = 'C__CATG__PASSWD';
    const CATG__SOA_STACKS = 'C__CATG__SOA_STACKS';
    const CATG__PLANNING = 'C__CATG__PLANNING';
    const CATG__ASSIGNED_CARDS = 'C__CATG__ASSIGNED_CARDS';
    const CATG__SIM_CARD = 'C__CATG__SIM_CARD';
    const CATG__TSI_SERVICE = 'C__CATG__TSI_SERVICE';
    const CATG__AUDIT = 'C__CATG__AUDIT';
    const CATG__NETWORK_PORT_OVERVIEW = 'C__CATG__NETWORK_PORT_OVERVIEW';
    const CATG__LOGICAL_UNIT = 'C__CATG__LOGICAL_UNIT';
    const CATG__ASSIGNED_LOGICAL_UNIT = 'C__CATG__ASSIGNED_LOGICAL_UNIT';
    const CATG__ASSIGNED_WORKSTATION = 'C__CATG__ASSIGNED_WORKSTATION';
    const CATG__VIRTUAL_TICKETS = 'C__CATG__VIRTUAL_TICKETS';
    const CATG__PERSON_ASSIGNED_WORKSTATION = 'C__CATG__PERSON_ASSIGNED_WORKSTATION';
    const CATG__CONTRACT_ASSIGNMENT = 'C__CATG__CONTRACT_ASSIGNMENT';
    const CATG__RACK_VIEW = 'C__CATG__RACK_VIEW';
    const CATG__MAIL_ADDRESSES = 'C__CATG__MAIL_ADDRESSES';
    const CATG__VOIP_PHONE = 'C__CATG__VOIP_PHONE';
    const CATG__VOIP_PHONE_LINE = 'C__CATG__VOIP_PHONE_LINE';
    const CATG__TELEPHONE_FAX = 'C__CATG__TELEPHONE_FAX';
    const CATG__SMARTCARD_CERTIFICATE = 'C__CATG__SMARTCARD_CERTIFICATE';
    const CATG__SHARE_ACCESS = 'C__CATG__SHARE_ACCESS';
    const CATG__VIRTUAL_SUPERNET = 'C__CATG__VIRTUAL_SUPERNET';
    const CATG__CERTIFICATE = 'C__CATG__CERTIFICATE';
    const CATG__SLA = 'C__CATG__SLA';
    const CATG__LDAP_DN = 'C__CATG__LDAP_DN';
    const CATG__VIRTUAL_AUTH = 'C__CATG__VIRTUAL_AUTH';
    const CATG__ADDRESS = 'C__CATG__ADDRESS';
    const CATG__MONITORING = 'C__CATG__MONITORING';
    const CATG__LIVESTATUS = 'C__CATG__LIVESTATUS';
    const CATG__VEHICLE = 'C__CATG__VEHICLE';
    const CATG__AIRCRAFT = 'C__CATG__AIRCRAFT';
    const CATG__NET_CONNECTIONS_FOLDER = 'C__CATG__NET_CONNECTIONS_FOLDER';
    const CATG__NET_LISTENER = 'C__CATG__NET_LISTENER';
    const CATG__NET_CONNECTOR = 'C__CATG__NET_CONNECTOR';
    const CATG__CLUSTER_ADM_SERVICE = 'C__CATG__CLUSTER_ADM_SERVICE';
    const CATG__JDISC_CA = 'C__CATG__JDISC_CA';
    const CATG__NDO = 'C__CATG__NDO';
    const CATG__CABLE = 'C__CATG__CABLE';
    const CATG__IDENTIFIER = 'C__CATG__IDENTIFIER';
    const CATG__SERVICE = 'C__CATG__SERVICE';
    const CATG__OPERATING_SYSTEM = 'C__CATG__OPERATING_SYSTEM';
    const CATG__JDISC_DISCOVERY = 'C__CATG__JDISC_DISCOVERY';
    const CATG__QINQ_SP = 'C__CATG__QINQ_SP';
    const CATG__FIBER_LEAD = 'C__CATG__FIBER_LEAD';
    const CATG__QINQ_CE = 'C__CATG__QINQ_CE';
    const CATG__IMAGES = 'C__CATG__IMAGES';
    const CATG__WAN = 'C__CATG__WAN';
    const CATG__RM_CONTROLLER = 'C__CATG__RM_CONTROLLER';
    const CATG__RM_CONTROLLER_BACKWARD = 'C__CATG__RM_CONTROLLER_BACKWARD';
    const CATG__MANAGED_OBJECTS = 'C__CATG__MANAGED_OBJECTS';
    const CATG__VRRP = 'C__CATG__VRRP';
    const CATG__VRRP_MEMBER = 'C__CATG__VRRP_MEMBER';
    const CATG__VRRP_VIEW = 'C__CATG__VRRP_VIEW';
    const CATG__STACK_MEMBER = 'C__CATG__STACK_MEMBER';
    const CATG__STACK_MEMBERSHIP = 'C__CATG__STACK_MEMBERSHIP';
    const CATG__LAST_LOGIN_USER = 'C__CATG__LAST_LOGIN_USER';
    const CATG__NET_ZONE = 'C__CATG__NET_ZONE';
    const CATG__NET_ZONE_OPTIONS = 'C__CATG__NET_ZONE_OPTIONS';
    const CATG__NET_ZONE_SCOPES = 'C__CATG__NET_ZONE_SCOPES';
    const CATG__STACK_PORT_OVERVIEW = 'C__CATG__STACK_PORT_OVERVIEW';
    const CATG__CABLE_CONNECTION = 'C__CATG__CABLE_CONNECTION';
    const CATG__MULTIEDIT = 'C__CATG__MULTIEDIT';
    const CATG__DATABASE_FOLDER = 'C__CATG__DATABASE_FOLDER';
    const CATG__DATABASE = 'C__CATG__DATABASE';
    const CATG__DATABASE_TABLE = 'C__CATG__DATABASE_TABLE';
    const CATG__DATABASE_SA = 'C__CATG__DATABASE_SA';
    const CATS__ENCLOSURE = 'C__CATS__ENCLOSURE';
    const CATS__ROOM = 'C__CATS__ROOM';
    const CATS__SERVICE = 'C__CATS__SERVICE';
    const CATS__SWITCH_NET = 'C__CATS__SWITCH_NET';
    const CATS__WAN = 'C__CATS__WAN';
    const CATS__EMERGENCY_PLAN = 'C__CATS__EMERGENCY_PLAN';
    const CATS__AC = 'C__CATS__AC';
    const CATS__ACCESS_POINT = 'C__CATS__ACCESS_POINT';
    const CATS__MONITOR = 'C__CATS__MONITOR';
    const CATS__CLIENT = 'C__CATS__CLIENT';
    const CATS__SWITCH_FC = 'C__CATS__SWITCH_FC';
    const CATS__ROUTER = 'C__CATS__ROUTER';
    const CATS__PRT = 'C__CATS__PRT';
    const CATS__FILE = 'C__CATS__FILE';
    const CATS__APPLICATION = 'C__CATS__APPLICATION';
    const CATS__NET = 'C__CATS__NET';
    const CATS__CELL_PHONE_CONTRACT = 'C__CATS__CELL_PHONE_CONTRACT';
    const CATS__LICENCE = 'C__CATS__LICENCE';
    const CATS__GROUP = 'C__CATS__GROUP';
    const CATS__LICENCE_LIST = 'C__CATS__LICENCE_LIST';
    const CATS__LICENCE_OVERVIEW = 'C__CATS__LICENCE_OVERVIEW';
    const CATS__FILE_ACTUAL = 'C__CATS__FILE_ACTUAL';
    const CATS__FILE_VERSIONS = 'C__CATS__FILE_VERSIONS';
    const CATS__FILE_OBJECTS = 'C__CATS__FILE_OBJECTS';
    const CATS__EMERGENCY_PLAN_ATTRIBUTE = 'C__CATS__EMERGENCY_PLAN_ATTRIBUTE';
    const CATS__EMERGENCY_PLAN_LINKED_OBJECTS = 'C__CATS__EMERGENCY_PLAN_LINKED_OBJECTS';
    const CATS__WS_NET_TYPE = 'C__CATS__WS_NET_TYPE';
    const CATS__WS_ASSIGNMENT = 'C__CATS__WS_ASSIGNMENT';
    const CATS__WS = 'C__CATS__WS';
    const CATS__UPS = 'C__CATS__UPS';
    const CATS__EPS = 'C__CATS__EPS';
    const CATS__SAN_ZONING = 'C__CATS__SAN_ZONING';
    const CATS__ORGANIZATION = 'C__CATS__ORGANIZATION';
    const CATS__ORGANIZATION_MASTER_DATA = 'C__CATS__ORGANIZATION_MASTER_DATA';
    const CATS__ORGANIZATION_PERSONS = 'C__CATS__ORGANIZATION_PERSONS';
    const CATS__PERSON = 'C__CATS__PERSON';
    const CATS__PERSON_MASTER = 'C__CATS__PERSON_MASTER';
    const CATS__PERSON_LOGIN = 'C__CATS__PERSON_LOGIN';
    const CATS__PERSON_ASSIGNED_GROUPS = 'C__CATS__PERSON_ASSIGNED_GROUPS';
    const CATS__PERSON_GROUP = 'C__CATS__PERSON_GROUP';
    const CATS__PERSON_GROUP_MASTER = 'C__CATS__PERSON_GROUP_MASTER';
    const CATS__PERSON_GROUP_MEMBERS = 'C__CATS__PERSON_GROUP_MEMBERS';
    const CATS__ORGANIZATION_CONTACT_ASSIGNMENT = 'C__CATS__ORGANIZATION_CONTACT_ASSIGNMENT';
    const CATS__PERSON_CONTACT_ASSIGNMENT = 'C__CATS__PERSON_CONTACT_ASSIGNMENT';
    const CATS__PERSON_GROUP_CONTACT_ASSIGNMENT = 'C__CATS__PERSON_GROUP_CONTACT_ASSIGNMENT';
    const CATS__CLUSTER_SERVICE = 'C__CATS__CLUSTER_SERVICE';
    const CATS__RELATION_DETAILS = 'C__CATS__RELATION_DETAILS';
    const CATS__DATABASE_SCHEMA = 'C__CATS__DATABASE_SCHEMA';
    const CATS__DATABASE_LINKS = 'C__CATS__DATABASE_LINKS';
    const CATS__DBMS = 'C__CATS__DBMS';
    const CATS__DATABASE_INSTANCE = 'C__CATS__DATABASE_INSTANCE';
    const CATS__PDU = 'C__CATS__PDU';
    const CATS__PDU_BRANCH = 'C__CATS__PDU_BRANCH';
    const CATS__PDU_OVERVIEW = 'C__CATS__PDU_OVERVIEW';
    const CATS__PARALLEL_RELATION = 'C__CATS__PARALLEL_RELATION';
    const CATS__DATABASE_OBJECTS = 'C__CATS__DATABASE_OBJECTS';
    const CATS__DATABASE_ACCESS = 'C__CATS__DATABASE_ACCESS';
    const CATS__DATABASE_GATEWAY = 'C__CATS__DATABASE_GATEWAY';
    const CATS__REPLICATION = 'C__CATS__REPLICATION';
    const CATS__REPLICATION_PARTNER = 'C__CATS__REPLICATION_PARTNER';
    const CATS__APPLICATION_ASSIGNED_OBJ = 'C__CATS__APPLICATION_ASSIGNED_OBJ';
    const CATS__CLUSTER_SERVICE_ASSIGNED_OBJ = 'C__CATS__CLUSTER_SERVICE_ASSIGNED_OBJ';
    const CATS__MIDDLEWARE = 'C__CATS__MIDDLEWARE';
    const CATS__KRYPTO_CARD = 'C__CATS__KRYPTO_CARD';
    const CATS__NET_IP_ADDRESSES = 'C__CATS__NET_IP_ADDRESSES';
    const CATS__NET_DHCP = 'C__CATS__NET_DHCP';
    const CATS__LAYER2_NET = 'C__CATS__LAYER2_NET';
    const CATS__LAYER2_NET_ASSIGNED_PORTS = 'C__CATS__LAYER2_NET_ASSIGNED_PORTS';
    const CATS__CONTRACT = 'C__CATS__CONTRACT';
    const CATS__CONTRACT_INFORMATION = 'C__CATS__CONTRACT_INFORMATION';
    const CATS__CONTRACT_ALLOCATION = 'C__CATS__CONTRACT_ALLOCATION';
    const CATS__CHASSIS = 'C__CATS__CHASSIS';
    const CATS__CHASSIS_SLOT = 'C__CATS__CHASSIS_SLOT';
    const CATS__CHASSIS_DEVICES = 'C__CATS__CHASSIS_DEVICES';
    const CATS__CHASSIS_VIEW = 'C__CATS__CHASSIS_VIEW';
    const CATS__CHASSIS_CABLING = 'C__CATS__CHASSIS_CABLING';
    const CATS__APPLICATION_VARIANT = 'C__CATS__APPLICATION_VARIANT';
    const CATS__BASIC_AUTH = 'C__CATS__BASIC_AUTH';
    const CATS__GROUP_TYPE = 'C__CATS__GROUP_TYPE';
    const CATS__LAYER2_NET_ASSIGNED_LOGICAL_PORTS = 'C__CATS__LAYER2_NET_ASSIGNED_LOGICAL_PORTS';
    const CATS__APPLICATION_SERVICE_ASSIGNED_OBJ = 'C__CATS__APPLICATION_SERVICE_ASSIGNED_OBJ';
    const CATS__APPLICATION_DBMS_ASSIGNED_OBJ = 'C__CATS__APPLICATION_DBMS_ASSIGNED_OBJ';
    const CATS__NET_ZONE = 'C__CATS__NET_ZONE';
    const CATS__OPERATING_SYSTEM = 'C__CATS__OPERATING_SYSTEM';
    const CATS__DATABASE_INSTALLATION = 'C__CATS__DATABASE_INSTALLATION';

}
