---
name: Main workflow

on:
  - push
  - pull_request

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4', '8.0', '8.1']
        experimental: [false]
        include:
          - versions: nightly
            experimental: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          update: true
          extensions: curl, date, dom, json, openssl, spl, xml, zlib
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Install composer
        uses: php-actions/composer@v6
        with:
          version: 2.x
      - name: Install dependencies
        run: composer install
      - name: Lint
        run: composer ci
